### ISSUE TITLE
Mine on iOS browser?

### ISSUE THREAD

**Issue by sunk818** [cazala/minero#1]
Can I mine on an iOS web browser? Safari chrome Firefox or other iOS browser? I can only see the Bitcoin icon and change to diff coin but nothing below that.

**Comment by rohmanhm** [comment]
Yes, you can.
`coin-hive` using javascript to mining crypto.

**Comment by cazala** [comment]
You can embed the miner on your website and it should work on mobile, although it will be slow.

**Comment by sunk818** [comment]
I copied your example on minero doesn't work for me

**Comment by cazala** [comment]
@sunk818 Hmm, it is a problem with cloudflare's https configuration, it is always redirecting to the homepage, even for the .js files. I just updated the homepage to use the http instead of https and disabled the https rules from cloudflare. Try again, but clean your cache first or use an incognite window.

**Comment by sunk818** [comment]
I still only get top part of screen but bottom doesn't appear where I can actually mine.
