### ISSUE TITLE
TOTAL HASHES and BALANCE not updating

### ISSUE THREAD

**Issue by Bosaa** [cazala/minero#5]
Hi,

i installed 3 days ago in my 4 website and i dont see the "TOTAL HASHES" and "BALANCE" updating only the HASHRATE
i can see that the HASHRATE get to 500HS to 1.5K but the "TOTAL HASHES" and "BALANCE" not updating and the "BALANCE" change from 0.00000592 XMR to 0.00000605 XMR and again to 0.00000592 XMR .. again and again ...
users reporting that minero.pw is a scam

**Comment by sunk818** [comment]
What currency did you ask to be paid in? Did you consider currency exchange rate (ShapeShift) can explain the difference? Also, mining difficulty changes which changes how many hashes you need for a payout.

**Comment by Bosaa** [comment]
i have BTC and XMR ...
you whant to say that HASHRATE 500HS and 1.5K gets only 30 K in the "TOTAL HASHES" ? and its not changing for d days ? 
miner.getStats() show that only me acceptedHashes: 1000 but no update in the "TOTAL HASHES"
and i dont know what is ShapeShift (sorry i'm noob ...)

**Comment by cazala** [comment]
Hi @Bosaa, are you the address 49fe...WCSG ? because i'm seeing something very weird in mineXMR.com... there's an address 4Gdo...4Unu which has 0H/s and 60G total hashes (and it says the last hash was submitted les than a minute ago).. and then there's a 49fe...WCSG with ~500H/s and 30K total hashes and it says it hasn't submitted a hash in 4 days.. which doesn't make any sense:

<img width="397" alt="screen shot 2017-10-16 at 8 16 23 pm" src="https://user-images.githubusercontent.com/2781777/31639409-e5c7d486-b2d8-11e7-8492-323970060e08.png">

To be honest, I don't know why is that happening... I can assure you that it is not a scam, all the code is hosted publicly so you can go see it yourself, but as I said in this projects readme, this is not rock solid, just something I did over the weekend.. the only thing I can tell you, if you want to still give it a try, is to change to a different address (that will be registered as a new worker in mineXRM.com, and it might get fixed)... but other than that, I dunno why the pool API is returning those stats..

**Comment by Bosaa** [comment]
@cazala thanks for the replay. yes 49fe...WCSG its me .. as i said i have 1 XMR and 1 BTC 141...oj3zR 
i started with the BTC and i saw that no updating and open XMR and then i saw the XMR not get updating
i just checked the 49fe...WCSG and i see 466.6666666666667 H/S  (i am in the site now as i said in the comment and i can see it run and no updating)

in minexmr.com you see its my score with my 2 GPU (using xmr-stak-nvidia) my problem is in minero.pw that i run the script in my websites but not getting nothing :\

**Comment by sunk818** [comment]
This is not an answer (only cazala knows), but maybe you can use coin-hive-stratum: https://github.com/cazala/coin-hive-stratum 

The usage example works for me, but I'm using on different pool not mineXMR. There's no UI for coin-hive-stratum example, but I've been submitting accepted hashes on 5 different mobile devices.

**Comment by cazala** [comment]
yep, I see those stats in mineXMR.com, you are getting the hashrate but not the hashes... for some reason all the hashes are being attributed to this 4Ggo worker: 

<img width="638" alt="screen shot 2017-10-16 at 9 38 16 pm" src="https://user-images.githubusercontent.com/2781777/31641498-51a4fa38-b2e5-11e7-80a1-fc0e8180db0d.png">

It doesn't even have a valid currency symbol (it says XRM instead of XMR). I don't know why is that happening, but it looks like an error with mineXMR's worker API (I register each minero.pw user as one worker for my master address) all the hashes are being attributed to the master address, but the workers don't have the right stats... I would suggest you to stop mining asap and go back to coinhive while I dig into this (or use coin-hive-stratum as sunk818 said), if I can't use the workers API I'll need to go back to the drawing board and probably create a master account for each user or something like that

**Comment by Bosaa** [comment]
i can use coinhive but i dont love when the antivirus alerting .. people get crazy when they see that alert :\
@sunk818 can you write what the address of the minero-api server you connect into ? 
@cazala thanks for checking this problem keep the good work !

**Comment by cazala** [comment]
I'll keep you posted, I think the best way will be to let the user provide a monero address.. this way we can even use mineXMR's UI and get all the features they provide that are not available to workers (like history and graphs and stuff). Maybe even let the user login with a now.sh account so you get you own server + proxy instances, that will make it way more scalable too (and it's still for free)

**Comment by Bosaa** [comment]
@cazala wow that sound good ! thank you, thank you, thank you !

**Comment by dennym** [comment]
Hey just reporting in with 49x2...9Zkt (XMR). Got I think the same issue. My initial test run brought these 10k hashes and .00000214 up then I deployed to live and its a bit active the only thing that changes is the the hashrate.
![screenshot from 2017-10-17 21 33 54](https://user-images.githubusercontent.com/1562328/31685710-48dcaf6e-b384-11e7-937e-a46ea93b3557.png)

**Comment by cazala** [comment]
@Bosaa so this is what I came up with: [CoinHive Proxy](https://coinhive-proxy.party).
